name: Build Android APK

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Unpack project
        run: |
          unzip -q *.zip -d . || true

      - name: Export to Android
        uses: firebelley/godot-export@v5.2.0
        with:
          godot: 4.7.2
          android: true
